# buildspec-deploy.yml
version: 0.2
env:
  exported-variables:
   - APP_URL
phases:
  install:
    steps:
      ## GITHUB ACTION INTEGRATION START ##
      # 1. GitHub Action: Install Kubectl
      - name: "Install Kubectl"
        uses: alexellis/arkade-get@23907b6f8cec5667c9a4ef724adea073d677e221 # ## THIS IS A GITHUB ACTION BEING RUN BY CODEBUILD ##
        with:
          kubectl: latest
      ## GITHUB ACTION INTEGRATION END ##

    commands: # These commands run after steps in the install phase
      - echo "Installing aws-iam-authenticator..."
      - curl -LO "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.6.11/aws-iam-authenticator_0.6.11_linux_amd64"
      - install -o root -g root -m 0755 aws-iam-authenticator_0.6.11_linux_amd64 /usr/local/bin/aws-iam-authenticator
      - PATH=$PATH:/usr/local/bin
      - echo "Installing Helm..."
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  pre_build:
    commands:
      # TARGET_REGION, EKS_CLUSTER_NAME, ECR_REPOSITORY_NAME, AWS_ACCOUNT_ID
      # are passed as environment variables from CodePipeline Action definition.
      # IMAGE_TAG is retrieved from CodeBuild's source version.
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - ECR_IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${TARGET_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${IMAGE_TAG}"
      - echo "Deploying to EKS cluster: ${EKS_CLUSTER_NAME} in region: ${TARGET_REGION}"
      - echo "Using ECR Image: ${ECR_IMAGE_URI}"
      - aws eks update-kubeconfig --name ${EKS_CLUSTER_NAME} --region ${TARGET_REGION}
  build:
    steps:
      ## GITHUB ACTION INTEGRATION START ##
      # 2. GitHub Action: Deploy Helm
      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.7 # ## THIS IS A GITHUB ACTION BEING RUN BY CODEBUILD ##
        with:
          aws-region: ${{ env.TARGET_REGION }} # Passed as env var from CodePipeline
          cluster-name: ${{ env.EKS_CLUSTER_NAME }} # Passed as env var from CodePipeline
          config-files: demo-app/values.yaml
          chart-path: demo-app/
          values: image.repository=${{ env.ECR_REPOSITORY_NAME }},image.tag=${{ env.IMAGE_TAG }}
          namespace: default
          name: demo-app
      ## GITHUB ACTION INTEGRATION END ##

      - name: "Fetch Application URL" # This is a regular run command, not a GitHub Action
        run: |
          while :;do url=$(kubectl get ingress/demo-app-ingress -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' -n default);
          [ -z "$url" ] && { echo "URL is empty, retrying in 5 seconds...";sleep 5;}||{ export APP_URL="$url";echo "APP_URL set to: $APP_URL";break;};
          done;echo "APP_URL=$APP_URL">>$GITHUB_ENV
  post_build:
    commands:
      - echo "Deployment to EKS in ${TARGET_REGION} complete."
