version: 0.2
env:
  exported-variables:
   - APP_URL
phases:
  install:
    commands:
      - echo "Installing kubectl, aws-iam-authenticator, and Helm..."
      # Install kubectl
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      # Install aws-iam-authenticator
      - curl -LO "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.6.11/aws-iam-authenticator_0.6.11_linux_amd64"
      - install -o root -g root -m 0755 aws-iam-authenticator_0.6.11_linux_amd64 /usr/local/bin/aws-iam-authenticator
      - PATH=$PATH:/usr/local/bin # Add to path
      # Install Helm
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  pre_build:
    commands:
      # TARGET_REGION, EKS_CLUSTER_NAME, ECR_REPOSITORY_NAME, AWS_ACCOUNT_ID
      # are passed as environment variables from CodePipeline Action definition.
      # IMAGE_TAG is retrieved from CodeBuild's source version.
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - ECR_IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${TARGET_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${IMAGE_TAG}"
      - echo "Deploying to EKS cluster: ${EKS_CLUSTER_NAME} in region: ${TARGET_REGION}"
      - echo "Using ECR Image: ${ECR_IMAGE_URI}"
      - aws eks update-kubeconfig --name ${EKS_CLUSTER_NAME} --region ${TARGET_REGION}
  build:
    commands:
      - echo "Deploying Helm chart..."
      - cd demo-app/ # Navigate into your Helm chart directory
      - helm upgrade --install demo-app .           --namespace default           --set image.repository=${ECR_REPOSITORY_NAME},image.tag=${IMAGE_TAG}           --set image.pullPolicy=Always # Ensures the latest image is always pulled
      - echo "Fetching Application URL..."
      - |
        # Loop until ingress hostname is available
        while :;do url=$(kubectl get ingress/demo-app-ingress -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' -n default);
        [ -z "$url" ] && { echo "URL is empty, retrying in 5 seconds...";sleep 5;}||{ export APP_URL="$url";echo "APP_URL set to: $APP_URL";break;};
        done;
        echo "APP_URL=${APP_URL}" >> $CODEBUILD_ENV_FILE # Export for CodePipeline output
  post_build:
    commands:
      - echo "Deployment to EKS in ${TARGET_REGION} complete."
